### PR TITLE
Added Readme for sharing and csv sharing schema

### PR DESCRIPTION
**Pull request by GauriSaran**
Added Readme for sharing specifications and sharing CSV schema.

### CODE REVIEW

**Comment by jeandavidt** [comment]
Hi Gauri!

On the whole I think this looks good! But I am having some trouble understanding how the schema would actually be applied.

I see that the schema explicitly names types of users in the .csv headers (local HA, PHAC, etc.) But in past discussions, we figured that pre-defining users might end up creating more confusion (for example, who or what is 'local_ha'?)

Also, I am not sure how the 'range' parameter would apply to most fields, since most fields can't really be ordred, and the data in some tables can't be ordred either (e.g., no site in the Site table comes 'before' another). What would a rule look like, say, if I want to allow acces for `site_1`and `site_3`, but not for `site_2`?. And do I need  WWMeasure data, SiteMeasure data, CPHD data and Sample data can be ordered by date (although, that requires some thought too, since these tables all have several datetime columns). Also, one can imagine wanting to sharing several ranges (e.g., all data between january and march, and all data between april and june), and I'm not sure this schema allows for that.

Also , how do the rules for sharing 'propagate' between tables? For example, say that I want to only share data from `site_2` and there are 20 samples in the sampe table that have that siteID and then 200 measures in WWMeasure that are related to the samples that that have the siteID - how do the WWMeasure rows get retained in the final dataset?

If you would like, we can discuss this maybe next Monday? :)

**Comment by GauriSaran** [comment]
Hi JeanDavit,
These are some excellent questions. I have answers for most except last one which I will need to figure out myself.
You asked how I define the access groups as in who is Local authority, who is provincial, etc?
I am actually not defining them. I will be making a web page form or portal where there will be a multiple checkbox list for the data curator to select access groups?
I thought that the data custodian will know who they are sharing it with? Like if it is with a local health authority, then they will choose that checkbox, if it is with Public health agency, then they can choose that as well so they can choose multiple options.
Once they enter the data and the schema filled in with who they want to share with, multiple datasets will be created and outputted as multiple excel workbooks for different access groups based on their selection. So this is more up to user what access group they consider the facility come under who they are sharing it with. I thought I could give few examples on there in description to let them know about what these access groups are by giving one or two examples. Then they can accordingly select one access group from check boxes based on who they are sharing with?

The next question about range is structured in the python code in a way that when schema is formed in a json dictionary, it is not going to consider the "range sharing properties" for those variables that have missing values. This is something I can add to the specification also to let the user know that they do not need to enter range for each and every variable.
Once the range for a particular variable is entered, then Pandas will be able to filter that range values out from the dataframe for that particular variable and give only that portion of the data.

As far as you mentioning about not including those observations that have certain values for a variable such as 'site1', 'site2', etc, that is also possible by creating another rule which I will that can be used by Pandas to filter out data based on those values of the variable. Then that particular observation will be filtered out. The only thing is to have the rules defined in schema.
The json dictionary with Pandas is able to filter things out for us.
For applying range schema with Pandas the columns do not need to be ordered by date. The range parameter will allow Pandas to use conditional coding to select data between those date values only. I am still working on this code. But this is feasible in Pandas.

For sharing several ranges, we will need to introduce, more range sharing properties. I believe this is something a data custodian can also do as to introducing more range properties for specific variables they wish to. However, the code is python will need to change or adjusted for adding more properties for sure.

The last question about connecting tables is something I need to think about. I did not think on that part yet. 
I hope what I wrote above answered most of your questions?
Please let me know if there is anything else that I can answer to clarify?

**Comment by GauriSaran** [comment]
Hi JeanDavit,

I spoke with Yulric this morning. He explained me more about how to proceed with specifications document. The objective portion of it and the milestones that have been set.
I will be working on the spec document more and will be creating a branch of sharing to send pull requests for each milestones that has been set for the spec document. 
The filter is definitely possible for range of values for only certain variables based on the CSV schema I created. However, I need to write the spec document in a bit more detail based on what Yulric shared for the milestones:
* Milestons
    * Outline all the functionality that you want to be part of this feature
    * Spec out how these features will used by a user. This would be the CSV file
* Spec out the function you will be writing
    * Inputs and outputs
    * Flow diagram (plantuml)
    * Test plan
    * Test cases
     * Write the function
 Once I finish the milestone for features functionality that user wants for sharing, then I will send next pull request to the sharing branch.
It would be nice to speak with you though to discuss further or explain this in the next meeting. 
Please let me know if you have any more questions regarding this PR.
Thank you.
Regards,
Gauri

**Comment by DougManuel** [comment]
@GauriSaran, the plan that you made with @yulric looks good. Do you want to close this PR? We can continue the discussion on your new PRs.

**Comment by yulric** [comment]
@GauriSaran I'll close this PR for now.

**Pull request closed without merging**
