### PR TITLE
ODM schematic

### PR DESCRIPTION
**Pull request by NielsNicolai**
Adds a schematic of the different data sources captured by the ODM in the 'README.md' file.

### CODE REVIEW

**Comment by jeandavidt** [comment]
In one of Monday's meetings, a few people mentioned that the table labels at thew far right seemed a bit 'cut off' from the rest of the figure by the hard edge of the map. Maybe the design could be adapted to avoid this?

**Comment by NielsNicolai** [comment]
@jeandavidt I agree that they are a bit "on the side" of the main figure. Was there any suggestion on how to improve this?

**Comment by jeandavidt** [comment]
I think they mentioned grouping Assay Method, WWm, reporter and instrument (in a bracket or a bubble maybe) and showing the link to"Lab" . We could also maybe make the edge of the map a bit thinner so it doesn't cause this "cut" in continuity, or maybe we can expand the map and have the four icons currently outside of the map, inside of it?

**Comment by NielsNicolai** [comment]
Ok, I'll try to have a look at before we publish our dataset.

**Review by DougManuel — APPROVED** [review]
Looks good. Ready for merge.

**Comment by NielsNicolai** [comment]
As suggested, I decreased the intensity of the map outline. I also tried to make a bracket that would not break the style for the icons on the right.

**Review by jeandavidt — APPROVED** [review]
Looks great :) Ready for merge

**Pull request merged**
